import {
  bindDomainResolvers,
  DOMAIN_VERSION,
  CRM_STAGES,
  LEAD_SOURCES,
  TASK_PRIORITIES,
  TASK_STATUS,
  OPERATION_TYPES,
  OPERATION_WORKFLOW_STATES,
  OPERATION_RISK_LEVELS,
  OPERATION_CHECKLIST_ITEMS,
  TRANSPORT_MODES,
  CURRENCIES,
  COUNTRIES,
  CUSTOMER_TYPES,
  PROVIDER_UNIT_TYPES,
  PROVIDER_UNIT_TYPE_LABELS,
  PROVIDER_AVAILABILITY,
  PROVIDER_COVERAGE_AREAS,
  PROVIDER_COVERAGE_OPTIONS,
  QUOTE_DEFAULT_MARGIN,
  EXTRA_HOURS_USD,
  CUSTOMS_STAY_USD,
  IVA_RATE,
  IMPORT_SPLITS,
  ENTITY_CONTRACTS,
  FIELD_ALIASES,
  getEntityContract,
  buildId,
  roundMoney,
  toNumber,
  normalizeText,
  getQuoteSplit,
  calculateQuote,
  normalizeRecord,
  normalizeActivityRecord,
  normalizeOperationChecklist,
  normalizeOperationRecord,
  getOperationChecklistProgress,
  getOperationAlerts,
  validateCrmRecord,
  validateQuoteRecord,
  validateTaskRecord,
  validateCustomerRecord,
  validateProviderRecord,
  validateOperationRecord,
  isToday,
  isDateBeforeToday
} from "./domain-core.js";

import {
  state,
  saveState,
  setSession,
  clearSession,
  setSetting,
  exportLocalBackup,
  importLocalBackup,
  upsertCrmRecord,
  upsertQuoteRecord,
  upsertTaskRecord,
  upsertOperationRecord,
  upsertCustomerRecord,
  upsertProviderRecord,
  getCrmById,
  getQuoteById,
  getTaskById,
  getOperationById,
  getCustomerById,
  getProviderById,
  listCrmRecords,
  listQuoteRecords,
  listTaskRecords,
  listOperationRecords,
  listCustomerRecords,
  listProviderRecords,
  listActivityRecords,
  getCustomerActivityFeed,
  getOperationActivityFeed,
  getDashboardMetrics,
  findCustomerIdByCompany,
  syncCustomerFromCrm
} from "./repository.local.js";

import {
  API_VERSION,
  API_BASE_PATH,
  API_ENVELOPE_VERSION,
  API_DEFAULT_LIMIT,
  API_ERROR_CODES,
  API_ENTITY_PATHS,
  SYNC_DIRECTIONS,
  ENTITY_SYNC_ORDER,
  getEntitySyncStrategy,
  getEntityEndpoints,
  getEntitySyncFilters,
  buildSyncManifest,
  buildSyncPullEnvelope,
  buildSyncPushEnvelope,
  buildApiSuccessEnvelope,
  buildApiErrorEnvelope,
  normalizeApiError,
  createFetchTransport,
  createNoopTransport,
  createApiAdapter,
  createCustomerApiAdapter,
  createQuoteApiAdapter,
  createTaskApiAdapter,
  createActivityApiAdapter,
  createOperationApiAdapter,
  toApiPayload,
  fromApiPayload,
  buildApiEnvelope
} from "./adapter.api.js";

bindDomainResolvers({
  getCustomerById,
  getOperationById,
  getExchangeRateUyu: () => state.settings.exchangeRateUyu
});

export function getSyncMode() {
  return String(state.settings.syncMode || "local").trim().toLowerCase();
}

export function getSyncBaseUrl() {
  return String(state.settings.syncBaseUrl || "").trim();
}

export function createConfiguredApiTransport(options = {}) {
  const syncMode = String(options.syncMode || getSyncMode() || "local").trim().toLowerCase();
  const baseUrl = Object.prototype.hasOwnProperty.call(options, "baseUrl") ? options.baseUrl : getSyncBaseUrl();

  if (syncMode === "api" || syncMode === "sync" || syncMode === "remote" || syncMode === "http") {
    return createFetchTransport({
      baseUrl,
      headers: options.headers,
      timeoutMs: options.timeoutMs,
      credentials: options.credentials,
      fetchImpl: options.fetchImpl,
      reason: options.reason
    });
  }

  return createNoopTransport({
    basePath: options.basePath || API_BASE_PATH,
    reason: options.reason || "sync-mode-local"
  });
}

export function createConfiguredApiAdapter(options = {}) {
  const transport = options.transport || createConfiguredApiTransport(options);
  return createApiAdapter({
    ...options,
    transport
  });
}

export {
  state,
  saveState,
  setSession,
  clearSession,
  setSetting,
  exportLocalBackup,
  importLocalBackup,
  DOMAIN_VERSION,
  CRM_STAGES,
  LEAD_SOURCES,
  TASK_PRIORITIES,
  TASK_STATUS,
  OPERATION_TYPES,
  OPERATION_WORKFLOW_STATES,
  OPERATION_RISK_LEVELS,
  OPERATION_CHECKLIST_ITEMS,
  TRANSPORT_MODES,
  CURRENCIES,
  COUNTRIES,
  CUSTOMER_TYPES,
  PROVIDER_UNIT_TYPES,
  PROVIDER_UNIT_TYPE_LABELS,
  PROVIDER_AVAILABILITY,
  PROVIDER_COVERAGE_AREAS,
  PROVIDER_COVERAGE_OPTIONS,
  QUOTE_DEFAULT_MARGIN,
  EXTRA_HOURS_USD,
  CUSTOMS_STAY_USD,
  IVA_RATE,
  IMPORT_SPLITS,
  ENTITY_CONTRACTS,
  FIELD_ALIASES,
  getEntityContract,
  buildId,
  roundMoney,
  toNumber,
  normalizeText,
  getQuoteSplit,
  calculateQuote,
  normalizeRecord,
  normalizeActivityRecord,
  normalizeOperationChecklist,
  normalizeOperationRecord,
  getOperationChecklistProgress,
  getOperationAlerts,
  validateCrmRecord,
  validateQuoteRecord,
  validateTaskRecord,
  validateCustomerRecord,
  validateProviderRecord,
  validateOperationRecord,
  isToday,
  isDateBeforeToday,
  upsertCrmRecord,
  upsertQuoteRecord,
  upsertTaskRecord,
  upsertOperationRecord,
  upsertCustomerRecord,
  upsertProviderRecord,
  getCrmById,
  getQuoteById,
  getTaskById,
  getOperationById,
  getCustomerById,
  getProviderById,
  listCrmRecords,
  listQuoteRecords,
  listTaskRecords,
  listOperationRecords,
  listCustomerRecords,
  listProviderRecords,
  listActivityRecords,
  getCustomerActivityFeed,
  getOperationActivityFeed,
  getDashboardMetrics,
  findCustomerIdByCompany,
  syncCustomerFromCrm,
  API_BASE_PATH,
  API_VERSION,
  API_ENVELOPE_VERSION,
  API_DEFAULT_LIMIT,
  API_ERROR_CODES,
  API_ENTITY_PATHS,
  SYNC_DIRECTIONS,
  ENTITY_SYNC_ORDER,
  getEntitySyncStrategy,
  getEntityEndpoints,
  getEntitySyncFilters,
  buildSyncManifest,
  buildSyncPullEnvelope,
  buildSyncPushEnvelope,
  buildApiSuccessEnvelope,
  buildApiErrorEnvelope,
  normalizeApiError,
  createFetchTransport,
  createNoopTransport,
  createApiAdapter,
  createCustomerApiAdapter,
  createQuoteApiAdapter,
  createTaskApiAdapter,
  createActivityApiAdapter,
  createOperationApiAdapter,
  toApiPayload,
  fromApiPayload,
  buildApiEnvelope
};
